name: build

on:
  release:
    types:
      - released
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: mamba-org/setup-micromamba@v1
        with:
          condarc: |
            channels:
              - conda-forge
          environment-name: build
          create-args: >-
            build
          cache-downloads: true
          cache-environment: true
          init-shell: >-
            bash
      - uses: actions/checkout@v4
      - run: build
      - uses: actions/upload-artifact@v4
        with:
          name: stormevents
          path: dist/
      - if: github.event_name == 'release' && github.event.action == 'released'
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
