name: build

on:
  release:
    types:
      - published

jobs:
  publish:
    name: publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: install Dunamai
        run: pip install dunamai
      - name: extract version from VCS
        run: poetry version $(dunamai from any)
      - name: build wheel and source
        run: poetry build
      - name: upload wheel and source
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
