name: build

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: mamba-org/setup-micromamba@v1
        with:
          condarc: |
            channels:
              - conda-forge
          environment-name: build
          create-args: >-
            build
          cache-downloads: true
          cache-environment: true
          init-shell: >-
            bash
      - uses: actions/checkout@v4
      - run: build
      - uses: actions/upload-artifact@v4
        with:
          name: stormevents
          path: dist/
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
