name: build

on:
  release:
    types:
      - published

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.x'
      - uses: actions/cache@main
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'setup.*') }}
      - run: pip wheel . --no-deps -w dist
      - uses: actions/upload-artifact@main
        with:
          name: package
          path: dist/
  publish:
    name: publish package
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.x'
      - uses: actions/cache@main
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'setup.*') }}
      - uses: actions/download-artifact@main
        with:
          name: package
          path: dist/
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
