name: tests

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**.py'
      - '.github/workflows/tests_simple.yml'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
      - name: load cached Python installation
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: lint-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: install linters
        run: pip install flake8 oitnb
      - name: lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: lint with oitnb
        run: oitnb . --check
  test_nonspatial:
    needs: lint
    name: test non-spatial conversions
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
      - name: load cached Python installation
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: test-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: install dependencies
        run: pip install ".[testing]"
      - name: run tests
        run: pytest --numprocesses auto -m "not spatial"
  test_spatial:
    needs: lint
    name: test spatial conversions
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
      - name: load cached Python installation
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: test-spatial-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: install dependencies
        run: pip install ".[testing,spatial]"
      - name: run tests
        run: pytest --numprocesses auto -m "spatial"
